"""Add activity_type column

Revision ID: 151a497b324a
Revises: 95c3d3fbef19
Create Date: 2026-01-31 20:34:53.829845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151a497b324a'
down_revision = '95c3d3fbef19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
