"""Add is_system to message

Revision ID: 95c3d3fbef19
Revises: f97f2714ffa7
Create Date: 2025-12-08 20:26:56.748701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95c3d3fbef19'
down_revision = 'f97f2714ffa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'BANNED', name='membershipstatus'),
               nullable=True)

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'BANNED', name='membershipstatus'),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warnings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'BANNED', name='membershipstatus'),
               nullable=False)
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activity_participants', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('ACTIVE', 'BANNED', name='membershipstatus'),
               nullable=False)
        batch_op.alter_column('warning_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
