"""Refactor associations to dedicated directory

Revision ID: e5a3aa22f4e4
Revises: ccbb5e4d0e1f
Create Date: 2025-07-24 18:38:11.314079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a3aa22f4e4'
down_revision = 'ccbb5e4d0e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
